POST http://localhost:8080/auth/sign-up
content-type: application/json

{
    "username": "test2",
    "password": "test123"
}

###

POST http://localhost:8080/auth/login
content-type: application/json

{
    "username": "test1",
    "password": "test123"
}

###

POST http://localhost:8080/auth/callback
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InRlc3QxIiwicGFzc3dvcmQiOiIkMmIkMTAkQ1JBSS5heVlLSEpKZWhadXV4MWl1ZW9XNnEwUnUudGx1QlZyVHF2MHJNU2thT3lkWGxrUkMiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTIwVDA1OjA3OjMxLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTIwVDA1OjA3OjMxLjAwMFoifSwiaWF0IjoxNjI5NDM4NjYyLCJleHAiOjE2Mjk0Mzg5NjJ9.BST0nz8GHnoAEOf1p9ofU_9XOoWbd42hVWLrcgSL6qw

###

GET http://localhost:8080/api/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJ1c2VybmFtZSI6InRlc3QyIiwicGFzc3dvcmQiOiIkMmIkMTAkUnBRSlJ4bVJYZ2QwYTQ1VGtUMmFlLmdVNS5xMy54VTFmaTNRMFIyZHBuR1hxcWNUQlJMN2EiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTIwVDA1OjUwOjU4LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTIwVDA1OjUwOjU4LjAwMFoifSwiaWF0IjoxNjI5NDM5Mzg1LCJleHAiOjE2Mjk0Mzk2ODV9.Oz6UuagJcGKnHN4OQBD8xcMSeonBGonthi4gkE3s7WY

###

GET http://localhost:8080/api/find/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InRlc3QxIiwicGFzc3dvcmQiOiIkMmIkMTAkQ1JBSS5heVlLSEpKZWhadXV4MWl1ZW9XNnEwUnUudGx1QlZyVHF2MHJNU2thT3lkWGxrUkMiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTIwVDA1OjA3OjMxLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTIwVDA1OjA3OjMxLjAwMFoifSwiaWF0IjoxNjI5NjE1ODc1LCJleHAiOjE2Mjk2MTYxNzV9.xISYBYtcglbvZTX-4riHfzbZieqp1Fn7JsTw86i4Q38

###

POST http://localhost:8080/api/new
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InRlc3QxIiwicGFzc3dvcmQiOiIkMmIkMTAkQ1JBSS5heVlLSEpKZWhadXV4MWl1ZW9XNnEwUnUudGx1QlZyVHF2MHJNU2thT3lkWGxrUkMiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTIwVDA1OjA3OjMxLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTIwVDA1OjA3OjMxLjAwMFoifSwiaWF0IjoxNjI5NjE1ODc1LCJleHAiOjE2Mjk2MTYxNzV9.xISYBYtcglbvZTX-4riHfzbZieqp1Fn7JsTw86i4Q38
content-type: application/json

{
    "text": "This is my nth Job"
}

###

DELETE http://localhost:8080/api/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InRlc3QxIiwicGFzc3dvcmQiOiIkMmIkMTAkTU1RNVdVVDl6emZZaW5Mcmdod3g1T2MxZWZxSzNnT3hPRGVGQWtpelQ3cWRtZUx3akx5NXkiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTEyVDEyOjMzOjUzLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTEyVDEyOjMzOjUzLjAwMFoifSwiaWF0IjoxNjI5Mjc2NjEwLCJleHAiOjE2MjkyNzY5MTB9.htgqkX9owOkwovIEFT8sXYmaw7YQygwb3y4dDU7lD8Y
content-type: application/json

###

PUT http://localhost:8080/api/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InRlc3QxIiwicGFzc3dvcmQiOiIkMmIkMTAkTU1RNVdVVDl6emZZaW5Mcmdod3g1T2MxZWZxSzNnT3hPRGVGQWtpelQ3cWRtZUx3akx5NXkiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTEyVDEyOjMzOjUzLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTEyVDEyOjMzOjUzLjAwMFoifSwiaWF0IjoxNjI5Mjc2NjEwLCJleHAiOjE2MjkyNzY5MTB9.htgqkX9owOkwovIEFT8sXYmaw7YQygwb3y4dDU7lD8Y
content-type: application/json

{
    "id": 6,
    "text": "This is edited"
}
