GET http://localhost:8080/api/all

###

GET http://localhost:8080/api/find/5

###

POST http://localhost:8080/api/new
content-type: application/json

{
    "text": "This is my nth Job"
}

###

DELETE http://localhost:8080/api/delete/8
content-type: application/json

###

PUT http://localhost:8080/api/edit
content-type: application/json

{
    "id": 7,
    "text": "This is Updated text 2"
}

###